FROM quay.io/exsules/base:alpine
MAINTAINER blazed@darkstar.se

RUN apk --update add \
  ca-certificates \
  ruby \
  ruby-bundler \
  ruby-dev \
  libpq \
  build-base \
  ruby-nokogiri \
  libffi-dev \
  tzdata \
  nodejs && \
  rm -rf /usr/share/ri && rm -rf /var/cache/apk/*

RUN mkdir -p /app

WORKDIR /tmp
RUN curl -sSL https://github.com/mailhog/MailHog/releases/download/v0.1.8/MailHog_linux_amd64 -o /usr/local/bin/mailhog && chmod +x /usr/local/bin/mailhog
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN gem install bundler
RUN bundle install --jobs 3 --retry 5

COPY . /app

WORKDIR /app

EXPOSE 3000 8025

ENTRYPOINT ["bundle", "exec"]

CMD ["foreman", "start", "-p", "3000"]